<?php

/**
 * This file was generated by the Laravel Make extension for Jetbrains IDEs.
 *
 * It enables the plugin to e.g. automatically refresh connected data sources
 * when migrations were executed. See
 *     https://plugins.jetbrains.com/plugin/14612-laravel-make
 * for more information.
 *
 * LARAVEL_MAKE_IDE_CONNECTOR_VERSION: 1.0.0
 */
class LaravelMakeIdeConnectorServiceProvider extends \Illuminate\Support\ServiceProvider
{
    public function boot()
    {
        if (!$this->app->runningInConsole()) {
            return;
        }

        $eventsFile = fopen(__DIR__ . '/ide_connector_latest_events.txt', 'w');
        if (!$eventsFile) return;

        \Event::listen('*', function ($eventName) use ($eventsFile) {
            $locked = flock($eventsFile, LOCK_EX);
            if (!$locked) return;

            fwrite($eventsFile, $eventName . "\n");
            flock($eventsFile, LOCK_UN);
        });
    }
}
